version: '3'

services:

  db:
    image: mysql:5.7
    container_name: opencart_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart

  web:
    image: php:8.1-apache
    container_name: opencart_web
    ports:
      - "8080:80"

    volumes:
      - ./opencart:/var/www/html

    depends_on:
      - db
