name: Selenium Automation Test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  selenium-test:

    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run Selenium Test
        run: mvn clean test "-DsuiteXmlFile=suites/search.xml"

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
